name: Build and deploy Java project to Azure Function App - testapk

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: testapk # set this to your function app name on Azure
  PACKAGE_DIRECTORY: '.' # set this to the directory which contains build.gradle file
  JAVA_VERSION: '17' # set this to the Java version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java SDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: 'Build with Gradle'
        run: |
          cd ${{ env.PACKAGE_DIRECTORY }}
          ./gradlew clean build --stacktrace --info

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D4BFAB94B8049A681253FD7C52E83A3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4D7BCAFC60FB4EB7BFB46ECD8121037F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1FD83D495C1D42C9BB98C09461B4AF7B }}
      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools

      - name: 'Deploy to Azure Function App'
        run: |
          cd ${{ env.PACKAGE_DIRECTORY }}
          func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} --java --verbose

      - name: 'Setup host.json'
        run: |
          cd ${{ env.PACKAGE_DIRECTORY }}
          # Replace the path accordingly if host.json is in a subdirectory
          cp ./host.json "${HOME}/host.json"  # Copy host.json to the home directory
          func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} --java --verbose --config-file "${HOME}/host.json"
      - name: 'Start the application'
        run: ' Azure
